In [92]:
import numpy as np
import pandas as pd

# 1- DataTypes & Attributes

In [27]:
# NumPy's data type is ndarray, this is the main data type in numpy
## => To Create a 1D numpy array : 
# IMPORTANT: IF YOU NEED TO DEFINE VECTOR, USE 1D NUMPY
A1D = np.array([1, 2, 3, 4])

In [28]:
## => To Check its type :
type(A1D)

numpy.ndarray

In [29]:
## => To Create a 2D numpy array :
# IMPORTANT: IF YOU NEED TO DEFINE MATRIX, USE 2D NUMPY
A2D = np.array( [ [1, 2, 3], [4, 5, 6] ] )
A2D.shape # 2-rows, 3-columns

(2, 3)

# 2- Manipulate NumPy Arrays

### 2.1- Arithmetic..

##### 2.1.1- Addition between vector and matrix

In [30]:
# if you need to add :
a1 = np.array([4, 6, 8])
A1 = np.array([[1, 1, 1],[1, 1, 1]])

In [31]:
# To Apply addition btn vector and matrix, each matrix row must have the same shape as vector:
# vector=[a1,a2,a3], matrix=[[A1,A2,A3],[A1,A2,A3]]
# Result=[[A1+a1, A2+a2, A3+a3],[...]] -> Same Shape as matrix
sum1 = a1 + A1
sum1

array([[5, 7, 9],
       [5, 7, 9]])

##### 2.1.2- Multiplication between vector and matrix

In [32]:
# *** THIS IS NOT MATRIX MULTIPLICATION ***
# * btn matrix and vector is done by multiply each item from vector to its corresponding item from matrix.
mul1 = a1 * A1 
mul1

array([[4, 6, 8],
       [4, 6, 8]])

### 2.1- Aggregation..
`Aggregation` : Perfoming same operation on a number of things 

In [33]:
x = np.array([1,3,5,7])


In [34]:
# sum(x) will find sum of all items and return the result
## ==> but always use python methods with python datatypes
sum(x)

16

In [35]:
# np.sum(x) will find sum of all items and return the result
## ==< but always use NumPy methods with Numpy arraies
np.sum(x)

16

In [36]:
x = np.array([[1,1,1],[1,1,1]])

In [37]:
np.mean(x)

1.0

In [38]:
np.max(x)

1

In [39]:
np.std(x)

0.0

# Exercise to wrap-up ..

In [50]:
# Generate Random values to be the prices for all items that sold on each day
np.random.seed(0)
sales_amount = np.random.randint(15, size=(5,3))

In [51]:
sales_amount

array([[12,  5,  0],
       [ 3, 11,  3],
       [ 7,  9,  3],
       [ 5,  2,  4],
       [ 7,  6,  8]])

In [52]:
# Generate the dataFrame and fill it with the random prices
Electronics_store = pd.DataFrame(
    sales_amount,
    index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
    columns=["GPS601", "GPS803", "GPS770"])

In [53]:
Electronics_store

GPS601  GPS803  GPS770
Mon        12       5       0
Tues        3      11       3
Wed         7       9       3
Thurs       5       2       4
Fri         7       6       8

In [58]:
# Generate Simple DataFrame to represent the price of each GPS type
# so the index is the price and the feature is the GPS type name
GPS_Price = np.array([490, 540, 620])
GPS_Price

array([490, 540, 620])

In [59]:
# Generate the DataFrame itself:
GPS_Prices = pd.DataFrame(
    GPS_Price,
    index=["Price"],
    columns=["GPS601", "GPS803", "GPS770"])
GPS_Prices

ValueError: Shape of passed values is (3, 1), indices imply (1, 3)

In [60]:
# it says that shape of GPS_Price NumPy array is 3*1 !
GPS_Price.shape

(3,)

In [67]:
# we need to handle the shape..
# ==> GPS_Price.reshape(1,3)
# then try to build the dataframe again
GPS_Prices = pd.DataFrame(
    GPS_Price.reshape(1,3),
    index=["Price"],
    columns=["GPS601", "GPS803", "GPS770"])
GPS_Prices


GPS601  GPS803  GPS770
Price     490     540     620

In [68]:
# WOW!!!
# our formula now to get the total_profit column for each day:
# Monday_Profit = GPS601_Price * Number_Of_Sold_Items_From_GPS601_At_Monday + same at Tuesday + same as wednesday + ... +same as Friday

#.. Lets Explore the shapes
Electronics_store.shape

(5, 3)

In [69]:
GPS_Prices.shape

(1, 3)

In [71]:
# to apply matrix multiplication which is (dot product) in NumPy:
# we need to transpose the GPS_Prices to be 3*1 ..
total_sales = Electronics_store.dot(GPS_Prices.T)
total_sales

Price
Mon     8580
Tues    9270
Wed    10150
Thurs   6010
Fri    11630

In [73]:
type(total_sales)

pandas.core.frame.DataFrame

In [76]:
# now we can add our new column to original dataframe
Electronics_store["$ Total Sales"] = total_sales

In [77]:
Electronics_store

GPS601  GPS803  GPS770  $ Total Sales
Mon        12       5       0           8580
Tues        3      11       3           9270
Wed         7       9       3          10150
Thurs       5       2       4           6010
Fri         7       6       8          11630

# Practical Example..
## In ML, we always need to convert whatever our data into numbers and provide these numbers to our model to train it, we can use NumPy to convert images into numbers, as each pixel has a color and each color has a number..

In [86]:
from IPython.display import Image
#from IPython.core.display import HTML 
Image(url= "./panda.png")


In [89]:

panda = imread('./panda.png')
panda


ModuleNotFoundError: No module named 'matplotlib'